version: "3.9"

services:
  autoriaApp:
    build:
      context: .
    ports:
      - "5678:8080"
    volumes:
      - ./backend:/autoriaApp
    restart: on-failure
    command: >
      sh -c "java -jar autoriaApp.jar"
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE = java_aws
      - MYSQL_USER = user
      - MYSQL_PASSWORD = password
      - MYSQL_ROOT_PASSWORD = superpassword
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: on-failure
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf